DROP TABLE account;
CREATE Table account(
	id VARCHAR(20) PRIMARY KEY,
	NAME VARCHAR(30) NOT NULL,
	balance INTEGER DEFAULT 0,
	TYPE VARCHAR(10),
	grade VARCHAR(10)
);

SELECT * FROM account;


CREATE TABLE MEMBER(

	id VARCHAR(50) PRIMARY KEY,
	NAME VARCHAR(100) NOT NULL,
	PASSWORD VARCHAR(50),
	email VARCHAR(100),
	address VARCHAR(200)
	);
	
	SELECT * FROM member;
	
	
	
DROP TABLE board;	
CREATE TABLE board(
	num INTEGER AUTO_INCREMENT PRIMARY KEY ,
	writer VARCHAR(50) REFERENCES member(id),
	SUBJECT VARCHAR(255),
	content VARCHAR(255),
	filename VARCHAR(100)
);

SELECT * FROM board;